In [1]:
import polars as pl
from procompa import get_project_root

PRJ_ROOT = get_project_root()
data_dir = PRJ_ROOT / "data"

In [3]:
CP_pdb_mapping = pl.read_csv("/cluster/project/beltrao/kdammer/master_thesis/data/complete_complex_pdb_mapping_v2/all_pdb_matches_with_match_class.csv")

In [6]:
CP_pdb_mapping["match_class"].unique()

shape: (6,)
Series: 'match_class' [str]
[
	"partial"
	"no_homology_match"
	"exact_homology_match"
	"superset"
	"no_sufficient_match"
	"exact_pdb_match"
]

In [7]:
intr_CP_pdb_mapping = CP_pdb_mapping.filter(pl.col("n_proteins") > 2).filter(pl.col("match_class") == "no_homology_match")

In [8]:
intr_CP_pdb_mapping.write_csv("/cluster/project/beltrao/kdammer/master_thesis/tmp/intr_CP_pdb_mapping.csv")

For how many complexes do i have paralogoues

In [3]:
para = pl.read_parquet(data_dir/"iPTM_and_pLDDT/Heterodimers_to_rereun_AF/CP_YM_complexes_pairs_rerun_AF.parquet")

In [4]:
para.head(3)

shape: (3, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Protein_1 ┆ Protein_2 ┆ Complex_p ┆ YM_comple ┆ … ┆ Para_exch ┆ Replaced_ ┆ AF_model_ ┆ pair_id  │
│ ---       ┆ ---       ┆ ortal_com ┆ x         ┆   ┆ ange      ┆ protein   ┆ exists    ┆ ---      │
│ str       ┆ str       ┆ plex      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆ ---       ┆ str       ┆   ┆ str       ┆ str       ┆ bool      ┆          │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ P0CX39    ┆ P33442    ┆ P05750    ┆           ┆ … ┆ null      ┆ null      ┆ false     ┆ P0CX39_P │
│           ┆           ┆ P05756    ┆           ┆   ┆           ┆           ┆           ┆ 33442    │
│           ┆           ┆ P05759    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ P25443    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ P2…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ P02309    ┆ Q12510    ┆           ┆ P31244    ┆ … ┆ null      ┆ null      ┆ false     ┆ P02309_Q │
│           ┆           ┆           ┆ P32558    ┆   ┆           ┆           ┆           ┆ 12510    │
│           ┆           ┆           ┆ Q04636    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ P40513    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Q1…       ┆   ┆           ┆           ┆           ┆          │
│ P0CX23    ┆ Q02486    ┆           ┆ P02400    ┆ … ┆ null      ┆ null      ┆ false     ┆ P0CX23_Q │
│           ┆           ┆           ┆ Q12000    ┆   ┆           ┆           ┆           ┆ 02486    │
│           ┆           ┆           ┆ P53551    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ P49167    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ O1…       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
para_swap = para.filter(~
    pl.col("Para_exchange").is_null() &
    pl.col("source").str.contains("Compl")
)

In [10]:
complexes_to_perform_para_swap_on = len(para_swap["complex_ac"].str.split("|").explode().unique().to_list())
complexes_to_perform_para_swap_on

38